apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "base"
  LOG_LEVEL: "INFO"
  KAFKA_BROKER: "kafka-broker:9092"
  ASR_ENGINE_URL: "http://asr-engine:8080"
  SPARK_PROCESSOR_URL: "http://spark-processor:7077"
