apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DISCORD_TOKEN: "replace-me"
  DEEPL_API_KEY: "replace-me"
  OPENAI_API_KEY: "replace-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: rundeck-auth
type: Opaque
stringData:
  RUNDECK_ADMIN_USERNAME: "admin"
  RUNDECK_ADMIN_PASSWORD: "replace-me"
